package projects.ids_wsn.nodeDefinitions.Monitor;

public enum Rules {
	REPETITION, DELAY, JAMMING, INTERVAL, TRANSMISSION_RANGE
}

/*  INTERVAL
	DELAY
	REPETITION
	RADIO TRANSMISSION RANGE
	JAMMING

	RETRANSMISSION
	INTEGRITY
	DESTINOS VALIDOS
	ORIGENS VALIDAS
*/